lib="/home/ec2-user/lambda/lib"
repos='http://cran.us.r-project.org'
source("http://bioconductor.org/biocLite.R")
biocLite("rhdf5",lib=lib)
install.packages("png",lib=lib, repos=repos)
install.packages("sp",lib=lib, repos=repos)
install.packages("rgdal",lib=lib, repos=repos)
install.packages("gstat",lib=lib, repos=repos)
install.packages("raster",lib=lib, repos=repos)
install.packages("fields",lib=lib, repos=repos)
install.packages("aws.s3",lib=lib, repos=repos)
install.packages("dplyr",lib=lib, repos=repos)
install.packages("geosphere",lib=lib, repos=repos)
install.packages("devtools", repos=repos)
library(devtools)
install_github("adokter/bioRad",lib=lib, repos=repos)
